pub const MAX_DECODED_BYTES: usize = 64 * 1024 * 1024;

pub const MAX_VIDEO_DECODED_BYTES: usize = MAX_DECODED_BYTES / 4 * 3;
pub const MAX_AUDIO_DECODED_BYTES: usize = MAX_DECODED_BYTES - MAX_VIDEO_DECODED_BYTES;

pub const MAX_INPUT_BYTES: usize = MAX_DECODED_BYTES;

pub const MAX_MSE_QUEUED_ENCODED_BYTES: usize = 256 * 1024 * 1024;

const _: () = {
    assert!(MAX_VIDEO_DECODED_BYTES + MAX_AUDIO_DECODED_BYTES == MAX_DECODED_BYTES);
    assert!(MAX_VIDEO_DECODED_BYTES > MAX_AUDIO_DECODED_BYTES);
    assert!(MAX_INPUT_BYTES == MAX_DECODED_BYTES);
    assert!(MAX_DECODED_BYTES == 64 * 1024 * 1024);
    assert!(MAX_MSE_QUEUED_ENCODED_BYTES == 256 * 1024 * 1024);
    assert!(MAX_MSE_QUEUED_ENCODED_BYTES > MAX_DECODED_BYTES);
};
